### ISSUE TITLE
Update packege to ZF3

### ISSUE THREAD

**Issue by RenatMagadiev** [jhuet/JhuZdtLoggerModule#5]
ZF3 ServiceManager use __invoke method please implemented it to support ZF3

**Comment by jhuet** [comment]
Hello @RenatMagadiev, unfortunatly, i haven't been able to follow the ZF3 changes. I would gladely take a PR to make this happen.

Thank you.

**Comment by MatthiasKuehneEllerhold** [comment]
Ive added a pull request for ZF3 in https://github.com/jhuet/JhuZdtLoggerModule/pull/6

**Comment by jhuet** [comment]
Thank you so much for your contribution on this @MatthiasKuehneEllerhold and also for the few small refactorings.

@RenatMagadiev, could you please have a look at his PR and see if it works fine for you ?

**Comment by RenatMagadiev** [comment]
@MatthiasKuehneEllerhold thank you. Everythink works ok so i'll close this issue.
